[2025-04-05T12:40:00.420+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T12:40:00.449+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:38:00+00:00 [queued]>
[2025-04-05T12:40:00.456+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:38:00+00:00 [queued]>
[2025-04-05T12:40:00.457+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T12:40:00.468+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_iot_producer_script> on 2025-04-05 12:38:00+00:00
[2025-04-05T12:40:00.473+0000] {standard_task_runner.py:63} INFO - Started process 753 to run task
[2025-04-05T12:40:00.476+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_data_pipeline', 'run_iot_producer_script', 'scheduled__2025-04-05T12:38:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/iot_data_dag.py', '--cfg-path', '/tmp/tmpx_ee2y_k']
[2025-04-05T12:40:00.478+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask run_iot_producer_script
[2025-04-05T12:40:00.524+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:38:00+00:00 [running]> on host aef507eba48f
[2025-04-05T12:40:00.595+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_data_pipeline' AIRFLOW_CTX_TASK_ID='run_iot_producer_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T12:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T12:38:00+00:00'
[2025-04-05T12:40:00.596+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T12:40:00.608+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-05T12:40:00.609+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/iot_producer_with_postgres.py']
[2025-04-05T12:40:00.622+0000] {subprocess.py:86} INFO - Output:
[2025-04-05T12:40:00.700+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/scripts/iot_producer_with_postgres.py': [Errno 2] No such file or directory
[2025-04-05T12:40:00.704+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-05T12:40:00.705+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T12:40:00.718+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-05T12:40:00.722+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=iot_data_pipeline, task_id=run_iot_producer_script, run_id=scheduled__2025-04-05T12:38:00+00:00, execution_date=20250405T123800, start_date=20250405T124000, end_date=20250405T124000
[2025-04-05T12:40:00.739+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task run_iot_producer_script (Bash command failed. The command returned a non-zero exit code 2.; 753)
[2025-04-05T12:40:00.768+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T12:40:00.782+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T12:40:00.783+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
