[2025-04-05T12:45:01.384+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T12:45:01.418+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:38:00+00:00 [queued]>
[2025-04-05T12:45:01.427+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:38:00+00:00 [queued]>
[2025-04-05T12:45:01.428+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-05T12:45:01.447+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_iot_producer_script> on 2025-04-05 12:38:00+00:00
[2025-04-05T12:45:01.456+0000] {standard_task_runner.py:63} INFO - Started process 1134 to run task
[2025-04-05T12:45:01.461+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_data_pipeline', 'run_iot_producer_script', 'scheduled__2025-04-05T12:38:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/iot_data_dag.py', '--cfg-path', '/tmp/tmpn1bqqyx8']
[2025-04-05T12:45:01.464+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask run_iot_producer_script
[2025-04-05T12:45:01.527+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:38:00+00:00 [running]> on host aef507eba48f
[2025-04-05T12:45:01.622+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_data_pipeline' AIRFLOW_CTX_TASK_ID='run_iot_producer_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T12:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T12:38:00+00:00'
[2025-04-05T12:45:01.623+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T12:45:01.638+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-05T12:45:01.638+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/scripts/iot_data_producer.py']
[2025-04-05T12:45:01.658+0000] {subprocess.py:86} INFO - Output:
[2025-04-05T12:45:01.761+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/dags/scripts/iot_data_producer.py': [Errno 2] No such file or directory
[2025-04-05T12:45:01.766+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-05T12:45:01.767+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T12:45:01.780+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-05T12:45:01.784+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=iot_data_pipeline, task_id=run_iot_producer_script, run_id=scheduled__2025-04-05T12:38:00+00:00, execution_date=20250405T123800, start_date=20250405T124501, end_date=20250405T124501
[2025-04-05T12:45:01.797+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task run_iot_producer_script (Bash command failed. The command returned a non-zero exit code 2.; 1134)
[2025-04-05T12:45:01.834+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T12:45:01.894+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T12:45:01.896+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
