[2025-04-05T12:42:55.740+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T12:42:55.772+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:36:00+00:00 [queued]>
[2025-04-05T12:42:55.780+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:36:00+00:00 [queued]>
[2025-04-05T12:42:55.781+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-04-05T12:42:55.792+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_iot_producer_script> on 2025-04-05 12:36:00+00:00
[2025-04-05T12:42:55.799+0000] {standard_task_runner.py:63} INFO - Started process 976 to run task
[2025-04-05T12:42:55.803+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'iot_data_pipeline', 'run_iot_producer_script', 'scheduled__2025-04-05T12:36:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/iot_data_dag.py', '--cfg-path', '/tmp/tmpvkxpy2fm']
[2025-04-05T12:42:55.805+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask run_iot_producer_script
[2025-04-05T12:42:55.857+0000] {task_command.py:426} INFO - Running <TaskInstance: iot_data_pipeline.run_iot_producer_script scheduled__2025-04-05T12:36:00+00:00 [running]> on host aef507eba48f
[2025-04-05T12:42:55.940+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='iot_data_pipeline' AIRFLOW_CTX_TASK_ID='run_iot_producer_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T12:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T12:36:00+00:00'
[2025-04-05T12:42:55.941+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T12:42:55.954+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-05T12:42:55.955+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/iot_data_producer.py']
[2025-04-05T12:42:55.968+0000] {subprocess.py:86} INFO - Output:
[2025-04-05T12:42:56.055+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/scripts/iot_data_producer.py': [Errno 2] No such file or directory
[2025-04-05T12:42:56.059+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-05T12:42:56.060+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T12:42:56.073+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-05T12:42:56.077+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=iot_data_pipeline, task_id=run_iot_producer_script, run_id=scheduled__2025-04-05T12:36:00+00:00, execution_date=20250405T123600, start_date=20250405T124255, end_date=20250405T124256
[2025-04-05T12:42:56.089+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task run_iot_producer_script (Bash command failed. The command returned a non-zero exit code 2.; 976)
[2025-04-05T12:42:56.135+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T12:42:56.154+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T12:42:56.155+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
